environment:
  CURL_VERSION: 7.39.0

install:
  - git submodule update --init --recursive
  - cd C:\projects\
  - if not exist ndi-sdk-slim.zip curl -kLO https://www.slepin.fr/obs-ndi/ci/ndi-sdk-slim.zip -f --retry 5 -C -
  - 7z x ndi-sdk-slim.zip -o"NDI_SDK"
  - if not exist dependencies2013.zip curl -kLO https://obsproject.com/downloads/dependencies2013.zip -f --retry 5 -C -
  - 7z x dependencies2013.zip -odependencies2013
  - if not exist qt570.zip curl -kLO https://www.slepin.fr/obs-websocket/ci/qt570.zip -f --retry 5 -C -
  - 7z x qt570.zip -o"Qt5.7.0"
  - set DepsPath32=%CD%\dependencies2013\win32
  - set DepsPath64=%CD%\dependencies2013\win64
  - set QTDIR32=%CD%\Qt5.7.0\msvc2013
  - set QTDIR64=%CD%\Qt5.7.0\msvc2013_64
  - set NDI_DIR=%CD%\NDI_SDK
  - set build_config=Release
  - git clone --recursive https://github.com/jp9000/obs-studio
  - cd C:\projects\obs-studio\
  - git checkout 18.0.0
  - mkdir build
  - mkdir build32
  - mkdir build64
  - cd ./build32
  - cmake -G "Visual Studio 12 2013" -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true ..
  - cd ../build64
  - cmake -G "Visual Studio 12 2013 Win64" -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true ..
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build64\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd C:\projects\obs-ndi\
  - mkdir build32
  - mkdir build64
  - cd ./build32
  - cmake -G "Visual Studio 12 2013" -DNDISDK_DIR="%NDI_DIR%" -DW32_PTHREADS_LIB="C:\projects\obs-studio\build32\deps\w32-pthreads\%build_config%\w32-pthreads.lib" -Dw32-pthreads_DIR="C:\projects\obs-studio\build32\deps\w32-pthreads" -DQTDIR="%QTDIR32%" -DLibObs_DIR="C:\projects\obs-studio\build32\libobs" -DLIBOBS_INCLUDE_DIR="C:\projects\obs-studio\libobs" -DLIBOBS_LIB="C:\projects\obs-studio\build32\libobs\%build_config%\obs.lib" -DOBS_FRONTEND_LIB="C:\projects\obs-studio\build32\UI\obs-frontend-api\%build_config%\obs-frontend-api.lib" ..
  - cd ../build64
  - cmake -G "Visual Studio 12 2013 Win64" -DNDISDK_DIR="%NDI_DIR%" -DW32_PTHREADS_LIB="C:\projects\obs-studio\build64\deps\w32-pthreads\%build_config%\w32-pthreads.lib" -Dw32-pthreads_DIR="C:\projects\obs-studio\build64\deps\w32-pthreads" -DQTDIR="%QTDIR64%" -DLibObs_DIR="C:\projects\obs-studio\build64\libobs" -DLIBOBS_INCLUDE_DIR="C:\projects\obs-studio\libobs" -DLIBOBS_LIB="C:\projects\obs-studio\build64\libobs\%build_config%\obs.lib" -DOBS_FRONTEND_LIB="C:\projects\obs-studio\build64\UI\obs-frontend-api\%build_config%\obs-frontend-api.lib" ..

build_script:
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-ndi\build32\obs-ndi.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-ndi\build64\obs-ndi.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

before_deploy:
  - 7z a "C:\projects\obs-ndi\build.zip" C:\projects\obs-ndi\release\*

deploy_script:
  - ps: Push-AppveyorArtifact "C:\projects\obs-ndi\build.zip" -FileName "obs-ndi-$(git log --pretty=format:'%h' -n 1).zip"

test: off

cache:
  - C:\projects\dependencies2013.zip
  - C:\projects\qt570.zip
  - C:\projects\ndi-sdk-slim.zip